---
title: "R Notebook"
output: html_notebook
---

```{r}
library(brms)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```


get data
```{r}

### bringing files for phenos, genos, K matrices
both.phenos <- as.matrix(read.csv(file="~/Documents/Lab Data/Daniele/big_hyps/big_hyps_associations/both.small.csv",row.names=1))
both.snps <- as.matrix(read.csv(file="~/Documents/Lab Data/Daniele/big_hyps/big_hyps_associations/both.snps.csv",row.names=1,as.is = TRUE))
both.snps.K <- as.matrix(read.csv(file="~/Documents/Lab Data/Daniele/big_hyps/big_hyps_associations/both.snps.K.csv",row.names = 1))

head(both.phenos)
head(both.snps[,1:10])
head(both.snps.K[,1:10])

both.phenos <- both.phenos[,-1]
both.snps.K <- both.snps.K[,-1]
```

merge
```{r}
both.snps.t <- t(both.snps)
row.names(both.snps.t) <- sub("X","",row.names(both.snps.t))
pheno.geno <- merge(both.phenos,both.snps.t,by="row.names")
head(pheno.geno[,1:10])
save(pheno.geno,file="pheno.geno.Rdata")
```
test how to make large formula
```{r}
my.formula <- as.formula(paste("high.RFR ~", paste(colnames(pheno.geno[10:209]),collapse="+")))
```

```{r}
brm1 <- brm(my.formula, data=pheno.geno,
            prior=c(
              set_prior("horseshoe(3,scale_global=0.1)",class="b"),
              set_prior("normal(3.5,1)",class="Intercept")
            ),
            sparse=TRUE,
            iter=20000,
            control = list(adapt_delta = 0.8)
)
brm1
```

