---
title: "Test rJAGs"
output: html_notebook
---

```{r}
library(rjags)
library(runjags)
```


```{r}
load("pheno.geno.Rdata")
geno.center <- geno*2-1
```

```{r}
head(pheno)
```

```{r}
head(geno.center[,1:10])
```

Try jags model using 100 predictors and full model

```{r}

N <- nrow(pheno)

p <- 100

jagmodel <- "
model {
 for(i in 1:N) {
   hyp[i] ~ dnorm(mu[i], tau)
   mu[i] <- a + inprod(geno[i,],b_geno)
 }
  for(j in 1:p) {
     b_geno[j] ~ dnorm(0,0.2)
  }
 a ~ dnorm(3,.2)
 tau <- pow(sigma,-2)
 sigma ~ dunif(0,15)
}

"
system.time(results <- run.jags(jagmodel,monitor=c("a","b_geno","sigma"),
                                method="parallel",
                                n.chains=4,
                                data=list(hyp=pheno[,"high.RFR"],
                                          geno=geno[,1:p],
                                          p=p,
                                          N=N)))
```

```{r}
summary(results)
plot(results,vars=c("a","sigma","b_geno[1]"))
```

Try with a 0/1 inclusion variable with a binomial dist centered at 0.01
```{r}
N <- nrow(pheno)

p <- 100

jagmodel <- "
model {
 for(i in 1:N) {
   hyp[i] ~ dnorm(mu[i], tau)
   mu[i] <- a + inprod(geno[i,],b_geno)
 }

  for(j in 1:p) {
     bT_geno[j] ~ dnorm(0,0.2)
     b_ind_geno[j] ~ dbern(0.01)
     b_geno[j] <- bT_geno[j] * b_ind_geno[j]
     
  }
 a ~ dnorm(3,.2)
 tau <- pow(sigma,-2)
 sigma ~ dunif(0,15)
}

"
system.time(results <- run.jags(jagmodel,monitor=c("a","b_geno","sigma"),
                                method="parallel",
                                n.chains=4,
                                data=list(hyp=pheno[,"high.RFR"],
                                          geno=geno[,1:p],
                                          p=p,
                                          N=N)))
```

```{r}
summary(results)
plot(results,vars=c("a","sigma","b_geno[1]"))
```

Try with hyperprior to determine sd of bT function

```{r}
N <- nrow(pheno)

p <- 100

jagmodel <- "
model {
 for(i in 1:N) {
   hyp[i] ~ dnorm(mu[i], tau)
   mu[i] <- a + inprod(geno[i,],b_geno)
 }

  for(j in 1:p) {
     bT_geno[j] ~ dnorm(0, b_tau)
     b_ind_geno[j] ~ dbern(0.01)
     b_geno[j] <- bT_geno[j] * b_ind_geno[j]
     
  }
 a ~ dnorm(3,.2)
 tau <- pow(sigma,-2)
 b_tau <- pow(b_sigma,-2)
 sigma ~ dunif(0,15)
 b_sigma ~ dunif(0,15)
pind~dbeta(2,8)
}

"
system.time(results <- run.jags(jagmodel,monitor=c("a","b_geno","sigma","b_tau","b_sigma"),
                                method="parallel",
                                n.chains=4,
                                data=list(hyp=pheno[,"high.RFR"],
                                          geno=geno[,1:p],
                                          p=p,
                                          N=N)))
```

```{r}
summary(results,vars=c("a","sigma","b_geno[1]"))
plot(results,vars=c("a","sigma","b_geno[1]"))
```



With hyperprior to determine dbern mean and b_T sd
```{r}
N <- nrow(pheno)

p <- 100

jagmodel <- "
model {
 for(i in 1:N) {
   hyp[i] ~ dnorm(mu[i], tau)
   mu[i] <- a + inprod(geno[i,],b_geno)
 }

  for(j in 1:p) {
     bT_geno[j] ~ dnorm(0, b_tau)
     b_ind_geno[j] ~ dbern(pind)
     b_geno[j] <- bT_geno[j] * b_ind_geno[j]
     
  }
 a ~ dnorm(3,.2)
 tau <- pow(sigma,-2)
 b_tau <- pow(b_sigma,-2)
 sigma ~ dunif(0,15)
 b_sigma ~ dunif(0,15)
 pind~dbeta(2,8)
}

"
system.time(results <- run.jags(jagmodel,monitor=c("a","b_geno","sigma","b_tau","b_sigma","pind"),
                                method="parallel",
                                n.chains=4,
                                data=list(hyp=pheno[,"high.RFR"],
                                          geno=geno[,1:p],
                                          p=p,
                                          N=N)))
```



